language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
  - pip install -r requirements.txt --use-mirrors
  - python setup.py install -q

# command to run tests, e.g. python setup.py test
script: python setup.py nosetests